### PR TITLE
Initial conversion to Dist-Zilla.

### LINKED ISSUE #14: Switch to use Dist::Zilla

### PR DESCRIPTION
**Pull request by shlomif**
https://metacpan.org/author/RRWO did not have a PluginBundle so I just
used some of my preferred defaults. Hope it is OK and, if not, I can
ammend it in future commits.

This aims to fix https://github.com/robrwo/Test-HTML-Spelling/issues/14 .

### CODE REVIEW

**Comment by shlomif** [comment]
Hi!

Why wasn't this pull-req merged yet? It's been over a month since I fixed the Travis-CI build. Please tend to it.

Regards,

-- @shlomif

**Comment by robrwo** [comment]
I've been very busy, and also without internet for several days.

**Comment by shlomif** [comment]
@robrwo : I see. Fair enough.

**Comment by robrwo** [comment]
Would you be interested in getting co-maint for the module and repo?

**Comment by shlomif** [comment]
@robrwo : I'd rather not become a comaint because I've started working on a somewhat competing/alternative module/framework for HTML spell checking, so there may be a conflict of interest. I don't mind waiting.

**Comment by robrwo** [comment]
@shlomif  This looks ok. Add something to the Changes file and I'm happy to merge it.

**Comment by shlomif** [comment]
@robrwo : I've added a "Changes" file note about dzil now.

**Comment by shlomif** [comment]
@robrwo: hi! Please merge this pull-req.

**Comment by shlomif** [comment]
On Thu, 26 Jan 2017 09:02:39 -0800
Robert Rothenberg <notifications@github.com> wrote:

> Merged #15.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)

The first phrase that needs to be taught when teaching a new language is how to
say “Do you speak English?”. The first thing that needs to be taught when
teaching a new computer tool is how to exit it.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Pull request merged**
